-- MySQL Script generated by MySQL Workbench
-- Fri Feb 10 18:12:47 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Pharmacy
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Pharmacy
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Pharmacy` DEFAULT CHARACTER SET utf8 ;
USE `Pharmacy` ;

-- -----------------------------------------------------
-- Table `Pharmacy`.`Person`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Pharmacy`.`Person` ;

CREATE TABLE IF NOT EXISTS `Pharmacy`.`Person` (
  `Fname` VARCHAR(45) NULL,
  `Minit` VARCHAR(1) NULL,
  `Lname` VARCHAR(45) NULL,
  `Ssn` VARCHAR(9) NOT NULL,
  `Address` VARCHAR(45) NULL,
  `Birth_Date` DATE NULL,
  PRIMARY KEY (`Ssn`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Pharmacy`.`Employee`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Pharmacy`.`Employee` ;

CREATE TABLE IF NOT EXISTS `Pharmacy`.`Employee` (
  `Salary` INT NULL,
  `Essn` VARCHAR(9) NOT NULL,
  PRIMARY KEY (`Essn`),
  CONSTRAINT `Essn`
    FOREIGN KEY (`Essn`)
    REFERENCES `Pharmacy`.`Person` (`Ssn`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Pharmacy`.`Order`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Pharmacy`.`Order` ;

CREATE TABLE IF NOT EXISTS `Pharmacy`.`Order` (
  `Order_Num` INT NOT NULL,
  `Price` INT NULL,
  `Date_Of_Purchase` DATE NULL,
  PRIMARY KEY (`Order_Num`))
ENGINE = InnoDB;

SET foreign_key_checks = 0;
-- -----------------------------------------------------
-- Table `Pharmacy`.`Clinic`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Pharmacy`.`Clinic` ;

CREATE TABLE IF NOT EXISTS `Pharmacy`.`Clinic` (
  `Address` VARCHAR(45) NOT NULL,
  `Number` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Address`, `Number`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Pharmacy`.`Customer`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Pharmacy`.`Customer` ;

CREATE TABLE IF NOT EXISTS `Pharmacy`.`Customer` (
  `Phone_Number` VARCHAR(10) NULL,
  `Next_Pickup` DATE NULL,
  `Cssn` VARCHAR(9) NOT NULL,
  `Orders` INT NULL,
  `Caddress` VARCHAR(45) NULL,
  PRIMARY KEY (`Cssn`),
  INDEX `Has_Order_idx` (`Orders` ASC) VISIBLE,
  INDEX `Prescribes_idx` (`Caddress` ASC) VISIBLE,
  CONSTRAINT `Cssn`
    FOREIGN KEY (`Cssn`)
    REFERENCES `Pharmacy`.`Person` (`Ssn`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Has_Order`
    FOREIGN KEY (`Orders`)
    REFERENCES `Pharmacy`.`Order` (`Order_Num`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Prescribes`
    FOREIGN KEY (`Caddress`)
    REFERENCES `Pharmacy`.`Clinic` (`Address`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Pharmacy`.`Pharm_Tech`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Pharmacy`.`Pharm_Tech` ;

CREATE TABLE IF NOT EXISTS `Pharmacy`.`Pharm_Tech` (
  `PTssn` VARCHAR(9) NOT NULL,
  `Certification` VARCHAR(45) NULL,
  PRIMARY KEY (`PTssn`),
  CONSTRAINT `PTssn`
    FOREIGN KEY (`PTssn`)
    REFERENCES `Pharmacy`.`Employee` (`Essn`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Pharmacy`.`Cashier`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Pharmacy`.`Cashier` ;

CREATE TABLE IF NOT EXISTS `Pharmacy`.`Cashier` (
  `CAssn` VARCHAR(9) NOT NULL,
  `Register #` INT NULL,
  PRIMARY KEY (`CAssn`),
  CONSTRAINT `CAssn`
    FOREIGN KEY (`CAssn`)
    REFERENCES `Pharmacy`.`Employee` (`Essn`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Pharmacy`.`Stocker`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Pharmacy`.`Stocker` ;

CREATE TABLE IF NOT EXISTS `Pharmacy`.`Stocker` (
  `STssn` VARCHAR(9) NOT NULL,
  `Section` VARCHAR(45) NULL,
  PRIMARY KEY (`STssn`),
  CONSTRAINT `STssn`
    FOREIGN KEY (`STssn`)
    REFERENCES `Pharmacy`.`Employee` (`Essn`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Pharmacy`.`Supplier`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Pharmacy`.`Supplier` ;

CREATE TABLE IF NOT EXISTS `Pharmacy`.`Supplier` (
  `Name` VARCHAR(45) NOT NULL,
  `Address` VARCHAR(45) NULL,
  `Phone_Number` VARCHAR(45) NULL,
  PRIMARY KEY (`Name`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Pharmacy`.`Product`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Pharmacy`.`Product` ;

CREATE TABLE IF NOT EXISTS `Pharmacy`.`Product` (
  `Name` VARCHAR(45) NOT NULL,
  `Dosage` VARCHAR(45) NULL,
  `Price` INT NULL,
  `Stock` INT NULL,
  `Manufacturer` VARCHAR(45) NULL,
  PRIMARY KEY (`Name`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Pharmacy`.`Products_Provided`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Pharmacy`.`Products_Provided` ;

CREATE TABLE IF NOT EXISTS `Pharmacy`.`Products_Provided` (
  `Pname` VARCHAR(45) NOT NULL,
  `Sname` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Pname`, `Sname`),
  INDEX `Sname_idx` (`Sname` ASC) VISIBLE,
  CONSTRAINT `Pname`
    FOREIGN KEY (`Pname`)
    REFERENCES `Pharmacy`.`Product` (`Name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Sname`
    FOREIGN KEY (`Sname`)
    REFERENCES `Pharmacy`.`Supplier` (`Name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Pharmacy`.`Active_Ingredients`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Pharmacy`.`Active_Ingredients` ;

CREATE TABLE IF NOT EXISTS `Pharmacy`.`Active_Ingredients` (
  `Ingredient` VARCHAR(45) NOT NULL,
  `Prod_Name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Ingredient`, `Prod_Name`),
  INDEX `Prod_Name_idx` (`Prod_Name` ASC) VISIBLE,
  CONSTRAINT `Prod_Name`
    FOREIGN KEY (`Prod_Name`)
    REFERENCES `Pharmacy`.`Product` (`Name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Pharmacy`.`Doctor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Pharmacy`.`Doctor` ;

CREATE TABLE IF NOT EXISTS `Pharmacy`.`Doctor` (
  `Dname` VARCHAR(45) NOT NULL,
  `Caddress` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Dname`, `Caddress`),
  INDEX `Caddress_idx` (`Caddress` ASC) VISIBLE,
  CONSTRAINT `Caddress`
    FOREIGN KEY (`Caddress`)
    REFERENCES `Pharmacy`.`Clinic` (`Address`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Pharmacy`.`Prescribes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Pharmacy`.`Prescribes` ;

CREATE TABLE IF NOT EXISTS `Pharmacy`.`Prescribes` (
  `Cssn` VARCHAR(45) NOT NULL,
  `Pname` VARCHAR(45) NOT NULL,
  `Clinic_Address` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Cssn`,`Pname`),
  INDEX `Product_idx` (`Pname` ASC) VISIBLE,
  INDEX `Clinic_idx` (`Clinic_Address` ASC) VISIBLE,
  CONSTRAINT `Customer`
    FOREIGN KEY (`Cssn`)
    REFERENCES `Pharmacy`.`Customer` (`Cssn`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Product`
    FOREIGN KEY (`Pname`)
    REFERENCES `Pharmacy`.`Product` (`Name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Clinic`
    FOREIGN KEY (`Clinic_Address`)
    REFERENCES `Pharmacy`.`Clinic` (`Address`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Pharmacy`.`Jobs`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Pharmacy`.`Jobs` ;

CREATE TABLE IF NOT EXISTS `Pharmacy`.`Jobs` (
  `STssn` VARCHAR(9) NOT NULL,
  `Product_Name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`STssn`, `Product_Name`),
  INDEX `Product_Name_idx` (`Product_Name` ASC) VISIBLE,
  CONSTRAINT `Stocker_ssn`
    FOREIGN KEY (`STssn`)
    REFERENCES `Pharmacy`.`Stocker` (`STssn`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Product_Name`
    FOREIGN KEY (`Product_Name`)
    REFERENCES `Pharmacy`.`Product` (`Name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Pharmacy`.`Buys`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Pharmacy`.`Buys` ;

CREATE TABLE IF NOT EXISTS `Pharmacy`.`Buys` (
  `Cssn` VARCHAR(9) NOT NULL,
  `ProdName` VARCHAR(45) NOT NULL,
  `Order_Num` INT NOT NULL,
  PRIMARY KEY (`Cssn`, `ProdName`),
  INDEX `Product_Name_idx` (`ProdName` ASC) VISIBLE,
  CONSTRAINT `Customer_Ssn`
    FOREIGN KEY (`Cssn`)
    REFERENCES `Pharmacy`.`Customer` (`Cssn`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `ProdName`
    FOREIGN KEY (`ProdName`)
    REFERENCES `Pharmacy`.`Product` (`Name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE = 1;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS = 1;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS = 1;
